package tool

/**
 * 页面路由
 */
sealed class Route(val route: String) {
    data object Start : Route("Start")
    data object Main : Route("Main")
    data object DeviceHistory : Route("DeviceHistory")
    data object DeviceInfo : Route("DeviceInfo")
    data object DeviceScan : Route("DeviceScan")
    data object DeviceConnect : Route("DeviceConnect")
    data object BluetoothPermission : Route("BlePermission")
    data object DeviceNetwork : Route("DeviceNetwork")
    data object DeviceContact : Route("DeviceContact")
    data object ContactIconSelect : Route("ContactIconSelect")
    data object DeviceFallAlert : Route("DeviceFallAlert")
    data object HomeBeaconGuide : Route("HomeBeaconIntroduction")
    data object HomeBeaconList : Route("HomeBeaconList")
    data object HomeBeaconAddGuide : Route("HomeBeaconAddGuide")
    data object HomeBeaconAdd : Route("HomeBeaconAdd")
    data object HomeBeaconQrGuide : Route("HomeBeaconQrGuide")
    data object HomeBeaconQr : Route("HomeBeaconQr")
    data object HomeBeaconScan : Route("HomeBeaconScan")
    data object HomeWifiGuide : Route("HomeWifiIntroduction")
    data object HomeWifiList : Route("HomeWifiList")
    data object HomeWifiManually : Route("HomeWifiManually")
    data object HomeWifiScan : Route("HomeWifiScan")
    data object MapAddress : Route("MapAddress")
    data object Faq : Route("Faq")
    data object Feedback : Route("Feedback")
    data object Language : Route("Language")
    data object ToolVersion : Route("ToolVersion")
    data object DeveloperLog : Route("DeveloperLog")
    data object TermsService : Route("TermsService")
    data object Apn : Route("Apn")
    data object Apns : Route("Apns")
    data object Server : Route("Server")
    data object CallSettings : Route("CallSettings")
    data object Volume : Route("Volume")
    data object PhoneOption : Route("PhoneOption")
    data object Button : Route("Button")
    data object Tilt : Route("Tilt")
    data object GeoFence : Route("GeoFence")
    data object GeoFenceEdit : Route("GeoFenceEdit")
    data object Motion : Route("Motion")
    data object NoMotion : Route("NoMotion")
    data object Leaves : Route("Leaves")
    data object LowBattery : Route("LowBattery")
    data object Clock : Route("Clock")
    data object ClockEdit : Route("ClockEdit")
    data object Welfare : Route("Welfare")
    data object OverSpeed : Route("OverSpeed")
    data object WorkMode : Route("WorkMode")
    data object ContinuousLocate : Route("ContinuousLocate")
    data object TimeZone : Route("TimeZone")
    data object AgpsLocation : Route("AgpsLocation")
    data object PositionManner : Route("PositionManner")
    data object BleWhiteList : Route("BleWhiteList")
    data object Sensitivity : Route("Sensitivity")
    data object NoDisturb : Route("NoDisturb")
    data object MoreSettings : Route("MoreSettings")
    data object VoicePrompt : Route("VoicePrompt")
    data object PowerOn : Route("PowerOn")
    data object WifiConnect : Route("WifiConnect")
    data object DeviceLanguage : Route("DeviceLanguage")
    data object DeviceBandSetting : Route("DeviceBandSetting")
    data object DeviceHeartRate : Route("DeviceHeartRate")
    data object DeviceStepCollect : Route("DeviceStepCollect")
    data object AllFun : Route("AllFun")
}